version: "3"

services:
  abraham:
    image: grin/abraham
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - lecrypt:/etc/letsencrypt
    environment:
      - FQDN=${FQDN}
      - EMAIL=${EMAIL}
volumes:
  lecrypt:
